curl https://rss.nytimes.com/services/xml/rss/nyt/World.xml > data/World.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Africa.xml > data/Africa.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/AsiaPacific.xml > data/AsiaPacific.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Europe.xml > data/Europe.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/MiddleEast.xml > data/MiddleEast.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Americas.xml > data/Americas.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Education.xml > data/Education.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/US.xml > data/US.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Politics.xml > data/Politics.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/NYRegion.xml > data/NYRegion.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Upshot.xml > data/Upshot.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Business.xml > data/Business.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/EnergyEnvironment.xml > data/EnergyEnvironment.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/SmallBusiness.xml > data/SmallBusiness.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Economy.xml > data/Economy.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/MediaandAdvertising.xml > data/MediaandAdvertising.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Dealbook.xml > data/Dealbook.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/YourMoney.xml > data/YourMoney.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml > data/Technology.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/PersonalTech.xml > data/PersonalTech.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Science.xml > data/Science.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Health.xml > data/Health.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Sports.xml > data/Sports.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Baseball.xml > data/Baseball.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/CollegeBasketball.xml > data/CollegeBasketball.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/CollegeFootball.xml > data/CollegeFootball.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Golf.xml > data/Golf.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Hockey.xml > data/Hockey.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/ProBasketball.xml > data/ProBasketball.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/ProFootball.xml > data/ProFootball.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Tennis.xml > data/Tennis.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Soccer.xml > data/Soccer.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Climate.xml > data/Climate.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Space.xml > data/Space.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Arts.xml > data/Arts.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/ArtandDesign.xml > data/ArtandDesign.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Books.xml > data/Books.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/SundayBookReview.xml > data/SundayBookReview.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Dance.xml > data/Dance.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Movies.xml > data/Movies.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Music.xml > data/Music.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Television.xml > data/Television.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/FashionandStyle.xml > data/FashionandStyle.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/DiningandWine.xml > data/DiningandWine.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Weddings.xml > data/Weddings.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/tmagazine.xml > data/tmagazine.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Travel.xml > data/Travel.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Theater.xml > data/Theater.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Jobs.xml > data/Jobs.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/RealEstate.xml > data/RealEstate.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Automobiles.xml > data/Automobiles.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Lens.xml > data/Lens.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/Obituaries.xml > data/Obituaries.xml &
curl https://content.api.nytimes.com/svc/news/v3/all/recent.rss &
curl https://rss.nytimes.com/services/xml/rss/nyt/MostEmailed.xml > data/MostEmailed.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/MostViewed.xml > data/MostViewed.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/MostShared.xml > data/MostShared.xml &
curl https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/charles-m-blow/rss.xml > data/charles-m-blow.rss.xml &
curl https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/jamelle-bouie/rss.xml > data/jamelle-bouie.rss.xml &
curl https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/david-brooks/rss.xml > data/david-brooks.rss.xml &
curl https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/frank-bruni/rss.xml > data/frank-bruni.rss.xml &
curl https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/gail-collins/rss.xml > data/gail-collins.rss.xml &
curl https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/ross-douthat/rss.xml > data/ross-douthat.rss.xml &
curl https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/maureen-dowd/rss.xml > data/maureen-dowd.rss.xml &
curl https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/thomas-l-friedman/rss.xml > data/thomas-l-friedman.rss.xml &
curl https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/michelle-goldberg/rss.xml > data/michelle-goldberg.rss.xml &
curl https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/ezra-klein/rss.xml > data/ezra-klein.rss.xml &
curl https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/nicholas-kristof/rss.xml > data/nicholas-kristof.rss.xml &
curl https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/paul-krugman/rss.xml > data/paul-krugman.rss.xml &
curl https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/farhad-manjoo/rss.xml > data/farhad-manjoo.rss.xml &
curl https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/bret-stephens/rss.xml > data/bret-stephens.rss.xml &
curl https://rss.nytimes.com/services/xml/rss/nyt/sunday-review.xml > data/sunday-review.xml &